github:
  user: "Theo13111"
  email: "elmaminer1@gmail.com."
  username: "Theo13111"
  token: "bb9b4781e5c845e1becee7a3e5a78bb5"
  branch: "master"
  owner: "jenkins-infra"
  repository: "jenkins.io"
